core/urls.py
from django.urls import include, path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    delete_review,
    edit_review,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    CategoryView,
    order_list_view,
    search,
    page_not_found
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('review/delete/<int:pk>/', delete_review, name='delete-review'),
    path('review/edit/<int:pk>/', edit_review, name='edit-review'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('newsletter/', include('newsletter.urls')),
    path('orders/', order_list_view, name='order-list'),
    path('search/', search, name='search'),
    path('page-not-found/', page_not_found , name='page_not_found'),
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from contact import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('newsletter/', include('newsletter.urls')),
    path('', include('contact.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
'''if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                            document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)'''

templates/delete_review.html
<!-- templates/delete_review.html -->
{% extends 'base.html' %}

{% block content %}
    <h2>Delete Review</h2>
    <p>Are you sure you want to delete this review?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
    <a href="{% url 'product' review.item.slug %}">Cancel</a>
{% endblock %}

templates/item_list.html
{% extends "base.html" %} {% block content %}

<h2>Here is the list of items</h2>

{% endblock content%}

templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background-color: rgb(173, 20, 243);
		color: black !important;
	}
	.topbar a:hover{
		color: black;
	}

	li a:hover {
		color: rgb(0, 0, 0); /* Color when hovered */
		text-decoration: none; /* Underline when hovered */
	}
</style>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			<div class="topbar">
				<div class="topbar-social">
					<a href="https://web.facebook.com/" target="_blank" class="topbar-social-item fab fa-facebook"></a>
					<a href="https://www.instagram.com/" target="_blank" class="topbar-social-item fab fa-instagram"></a>
					<a href="https://x.com/" target="_blank" class="topbar-social-item fab fa-twitter"></a>
					<a href="https://www.youtube.com/" target="_blank" class="topbar-social-item fab fa-youtube"></a>
				</div>

				<span class="topbar-child1" style="color: white; font-weight: bold;">
					Free shipping for standard order over $1599.99
				</span>

				

				
			</div>

			<div class="wrap_header">
				<!-- Logo -->
				<a href="/" class="logo" style="color: black; text-decoration: none;">
					<p style="color: black; "><b style="font-size: 22px;">Tech Giants</b>
				</a>

				

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
							
							<li>
								<a href="/" style="
								display: inline-block;
								padding: 5px 20px;
								border: 0px solid black;
								border-radius: 0px;
								color: black;
								text-decoration: none;
								background-color: white;
								transition: background-color 0.3s, color 0.3s;
							" onmouseover="this.style.backgroundColor='black'; this.style.color='white';" onmouseout="this.style.backgroundColor='white'; this.style.color='black';">Home</a>

							</li>

							<li>
								<a href="/shop/" style="
								display: inline-block;
								padding: 5px 20px;
								border: 0px solid black;
								border-radius: 0px;
								color: black;
								text-decoration: none;
								background-color: white;
								transition: background-color 0.3s, color 0.3s;
							" onmouseover="this.style.backgroundColor='black'; this.style.color='white';" onmouseout="this.style.backgroundColor='white'; this.style.color='black';">Shop</a>
							</li>


							<!--{% categories %}-->
							<li>
								<a href="#" style="
								display: inline-block;
								padding: 5px 20px;
								border: 0px solid black;
								border-radius: 0px;
								color: black;
								text-decoration: none;
								background-color: white;
								transition: background-color 0.3s, color 0.3s;
							" onmouseover="this.style.backgroundColor='black'; this.style.color='white';" onmouseout="this.style.backgroundColor='white'; this.style.color='black';">Categories</a>
								<ul class="sub_menu">
									<li><a href="/category/phone/">Phones</a></li>
									<li><a href="/category/laptop/">Laptops</a></li>
								</ul>
							</li>

							


							<li>
								<a href="/contact/" style="
								display: inline-block;
								padding: 5px 20px;
								border: 0px solid black;
								border-radius: 0px;
								color: black;
								text-decoration: none;
								background-color: white;
								transition: background-color 0.3s, color 0.3s;
							" onmouseover="this.style.backgroundColor='black'; this.style.color='white';" onmouseout="this.style.backgroundColor='white'; this.style.color='black';">Contact</a>
							</li>

							 {% if request.user.is_authenticated %}

							<li>
								<!--div class="header-wrapicon2">
									<a href="/orders/">
										<img src="{% static '\images\icons\icon-header-02.jpg' %}" class="header-icon1 js-show-header-dropdown" height="100%" alt="ICON">
									</a>
								</div-->

								<a href="/orders/" style="
								display: inline-block;
								padding: 5px 20px;
								border: 0px solid black;
								border-radius: 0px;
								color: black;
								text-decoration: none;
								background-color: white;
								transition: background-color 0.3s, color 0.3s;
							" onmouseover="this.style.backgroundColor='black'; this.style.color='white';" onmouseout="this.style.backgroundColor='white'; this.style.color='black';">Orders</a>
							</li>
							
							<li>
								<div class="header-wrapicon2">
								<a href="{% url 'core:order-summary' %}">
									
									<img src="{% static 'images\icons\cart.jpg' %}" class="header-icon1 js-show-header-dropdown" height="100%" alt="ICON">
						<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>
									</a>
								</div>
							</li>

							<li>
								<a href="{% url 'account_logout' %}" style="
								display: inline-block;
								padding: 5px 20px;
								border: 0px solid black;
								border-radius: 0px;
								color: black;
								text-decoration: none;
								background-color: white;
								transition: background-color 0.3s, color 0.3s;
							" onmouseover="this.style.backgroundColor='black'; this.style.color='white';" onmouseout="this.style.backgroundColor='white'; this.style.color='black';">Logout</a>
							</li>
							{% else %}
							<li>
								<a href="#" style="
								display: inline-block;
								padding: 5px 20px;
								border: 0px solid black;
								border-radius: 0px;
								color: black;
								text-decoration: none;
								background-color: white;
								transition: background-color 0.3s, color 0.3s;
							" onmouseover="this.style.backgroundColor='black'; this.style.color='white';" onmouseout="this.style.backgroundColor='white'; this.style.color='black';">Login</a>
								<ul class="sub_menu">
									<li><a href="{% url 'account_login' %}">Login</a></li>
									<li><a href="{% url 'account_signup' %}">SignUp</a></li>
								</ul>
							</li>
							{% endif %} 
						</ul>
					</nav>
				</div>

				<!-- Icons -->
				<div class="d-flex align-items-center ml-5">
					<a href="#" class="icon-link search-icon mr-3 text-dark">
						<i class="fa fa-search"></i>
					</a>
					<div class="search-form">
						<form method="GET" action="{% url 'core:search' %}">
							<input type="text" name="q" placeholder="Search for products...">
							<button type="submit">Search</button>
						</form>
					</div>
					<a href="#" class="icon-link mr-3 text-dark">
						<i class="fa fa-heart"></i>
					</a>
					<a href="#" class="icon-link mr-3 text-dark">
						<i class="fa fa-shopping-cart"></i>
						
					</a>
					<div class="ml-4">

					
					{% if request.user.is_authenticated %}
					
					
					{% else %}
					
					<a href="{% url 'account_signup' %}" class=" ml-3" style="background-color:black;padding: 9px 20px;color:white;">Sign Up</a>
					{% endif %}
				</div>
				</div>

				<style>
					/* Your existing styles */
					.search-form {
						display: none;
						position: absolute;
						top: 100%;
						left: 0;
						background-color: #fff;
						padding: 10px;
						box-shadow: 0 2px 4px rgba(0,0,0,0.1);
					}
					
					.search-form input[type="text"],
					.search-form button {
						margin-right: 5px;
					}
					
					</style>
					
					<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
					<script>
					$(document).ready(function() {
						$('.search-icon').click(function(e) {
							e.preventDefault();
							$('.search-form').slideToggle('fast');
						});
					});
					</script>
				
			</div>
		</div>

		<div class="topbar">
			

			<span class="topbar-child1" style="color: white; font-weight: bold;">
				Free shipping for standard order over $1599.99
			</span>

			

			
		</div>
		<!-- Header Mobile -->
		<div class="wrap_header_mobile">

			<!-- Logo moblie -->
			<a href="/" class="logo-mobile"style="
								display: inline-block;
								padding: 5px 20px;
								border: 0px solid black;
								border-radius: 0px;
								color: black;
								text-decoration: none;
								background-color: white;
								transition: background-color 0.3s, color 0.3s;
							" onmouseover="this.style.backgroundColor='black'; this.style.color='white';" onmouseout="this.style.backgroundColor='white'; this.style.color='black';"><h3 style="font-weight: bold;font-size:20px;">Tech Giants</h3> </a>

				<!--img src="{% static 'images/icons/logo.png' %}" alt="IMG-LOGO"-->
			</a>


			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					<a href="{% url 'account_signup' %}" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide2"></span>

					<div class="header-wrapicon2">
						<a href="/orders/" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-02old.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						</a>
					</div>
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">

					<!--li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								fashe@example.com
							</span>

							<div class="topbar-language rs1-select2">
								<select class="selection-1" name="time">
									<option>USD</option>
									<option>EUR</option>
								</select>
							</div>
						</div>
					</li-->

					<li class="item-menu-mobile">
						<a href="/">Home</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">Shop</a>
					</li>

					{% categories_mobile %}

					<li class="item-menu-mobile">
						<a href="/contact/">Contact</a>
					</li>

					{% if request.user.is_authenticated %}
					<li class="item-menu-mobile">
						<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
					</li>
					<li class="item-menu-mobile">
						<a href="{% url 'account_logout' %}">Logout</a>
					</li>
					{% else %}
					<li class="item-menu-mobile">
						<a href="/accounts/login/">Login</a>
						<ul class="sub-menu">
							<li><a href="{% url 'account_login' %}">Login</a></li>
							<li><a href="{% url 'account_signup' %}">SignUp</a></li>
						</ul>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>
					{% endif %}

				</ul>
			</nav>
		</div>
	</header>

templates/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}


    </style>
  
 
    

   

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{ order.get_total }}</strong>
        </li>
      </ul>
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>Order Summary</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Qty</th>
            <th scope="col">Total Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
			<img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
            </td>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
            	<a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
            	{{ order_item.quantity }}
            	<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-3"></i></a>
            </td>
            <td>
              {% if order_item.item.discount_price %}
                  ${{ order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary">  Saving ${{ order_item.get_amount_saved }}</span>
              {% else %}
                  ${{ order_item.get_total_item_price}}
              {% endif %}
              <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
              	<i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
			<td colspan="5">Your cart is empty</td>
          </tr>
        </tbody>
        {% endfor %}
        {% if object.coupon %}
        <tr>
          <td colspan="5"><b>Coupon : </b></td>
          <td>- ${{ object.coupon.amount }}</td>
        </tr>
        {% endif%}
        {% if object.get_total %}
        <tr>
        	<td colspan="5"><b>Order Total : </b></td>
        	<td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
        	<td colspan="5">
        		<a href="/checkout" class="btn btn-warning float-right ml-2">Checkout</a>
        		<a href="/" class="btn btn-primary float-right">Continue Shopping</a>

        	</td>
        </tr>
        {% endif %}
      </table>
    </div>
  </div>
</div>

{% endblock content %}

templates/product-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<!-- breadcrumb -->
	<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
		<a href="/" class="s-text16">
			Home
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<a href="{% url 'core:category' object.category.slug %}" class="s-text16">
			{{ object.category }}
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<span class="s-text17">
			{{object.title}}
		</span>
	</div>

	<!-- Product Detail -->
	<div class="container bgwhite p-t-35 p-b-80">
		<div class="flex-w flex-sb">
			<div class="w-size13 p-t-30 respon5">
				<div class="wrap-slick3 flex-sb flex-w">
					<div class="wrap-slick3-dots"></div>

					<div class="slick3">
						<div class="item-slick3" data-thumb="{{ object.image.url }}">
							<div class="wrap-pic-w">
								<img src="{{ object.image.url }}" alt="{{ object.title }}">
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="w-size14 p-t-30 respon5">
				<h4 class="product-detail-name m-text16 p-b-13">
					{{object.title}}
				</h4>

				
				{% if object.discount_price %}
								<span class="block2-oldprice m-text7 p-r-5" style="font-size: 1.5rem;">
									${{ object.price }}
								</span>

								<span class="block2-newprice m-text8 p-r-5" style="font-size: 1.5rem;">
									${{ object.discount_price }}
								</span>
								{% else %}
								<span class="m-text17">
									${{object.price}}
								</span>
								{% endif %}

				<p class="s-text8 p-t-10">
					{{ object.description_short }}
				</p>

				<!--  -->
				<div class="p-t-33 p-b-60">

					<div class="flex-r-m flex-w p-t-10">
						<div class="w-size16 flex-m flex-w">
							<div class="flex-w bo5 of-hidden m-r-22 m-t-10 m-b-10">
								<button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-minus" aria-hidden="true"></i>
								</button>

								<input class="size8 m-text18 t-center num-product" type="number" name="num-product" value="1">

								<button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-plus" aria-hidden="true"></i>
								</button>
							</div>
							
							<div class="btn-addcart-product-detail size9 trans-0-4 m-t-10 m-b-10" style="margin-bottom: 20px;">
								<!-- Button -->
								
								
								
							</div>
							
							<a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary" style="margin: 2px;">Add to Cart</a>
							<a href="{{object.get_remove_from_cart_url}}" class="btn btn-outline-dark" style="margin: 2px;">Remove from Cart</a>
						</div>
					</div>
				</div>
				<br>
				<div class="p-b-45">
					<span class="s-text8 m-r-35">SKU: {{ object.stock_no }}</span>
					<span class="s-text8">Categories: {{ object.category }}</span>
				</div>
			</div>
		</div>
	</div>

	<section>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
		<style>
			h2 {
				border-bottom: 2px solid #f1f1f1;
				padding-bottom: 10px;
				color: #007BFF;
			}
			h4 {
				border-bottom: 2px solid #f1f1f1;
				padding-bottom: 10px;
				color: #000a38;
			}
			.description {
				margin: 20px 0;
				text-align: justify;
			}
			.reviews {
				margin: 20px 0;
			}
			.review {
				border-bottom: 1px solid #f1f1f1;
				padding: 10px 0;
			}
			.review p {
				margin: 5px 0;
			}
			.review strong {
				color: #007BFF;
			}
			.review small {
				color: #999;
			}
			.review-form {
				margin: 20px 0;
			}
			.review-form button {
				background-color: #007BFF;
				color: #fff;
				border: none;
				padding: 10px 20px;
				cursor: pointer;
				border-radius: 5px;
			}
			.review-form button:hover {
				background-color: #0056b3;
			}
			.form-control {
            width: 100%;
            padding: 10px;
            margin: 5px 0 15px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
			}

			.form-control:focus {
				border-color: #4CAF50;
				outline: none;
			}

			textarea.form-control {
				resize: vertical;
			}

			.star-rating .fa-star {
				font-size: 2em;
				color: gray;
				cursor: pointer;
			}

			.star-rating .fa-star.checked {
				color: orange;
			}
		</style>

		<div class="container">
			<div style="margin-top: -5%;">
				<h2>Description</h2>
				<div class="description">
					<p style="color: black;">
						{{ object.description_long|safe }}
					</p>
				</div>
			</div>

			<h2 style="margin-top: 10%;">Reviews</h2>
			<div class="reviews">
				{% for review in reviews %}
					<div class="review">
						{% if review.rating == 5 %}
							<p style="color: #000000;"><strong>{{ review.user.username }}</strong> rated it ★★★★★</p>
						{% elif review.rating == 4 %}
							<p style="color: #000000;"><strong>{{ review.user.username }}</strong> rated it ★★★★☆</p>
						{% elif review.rating == 3 %}
							<p style="color: #000000;"><strong>{{ review.user.username }}</strong> rated it ★★★☆☆</p>
						{% elif review.rating == 2 %}
							<p style="color: #000000;"><strong>{{ review.user.username }}</strong> rated it ★★☆☆☆</p>
						{% elif review.rating == 1 %}
							<p style="color: #000000;"><strong>{{ review.user.username }}</strong> rated it ★☆☆☆☆</p>
						{% endif %}
						<p style="color: #000000;">{{ review.comment }}</p>
						<p><small>Posted on {{ review.created_at }}</small></p>
						{% if review.user == request.user %}
						<div>
                    		<form method="post" action="{% url 'core:delete-review' review.pk %}">
                        		{% csrf_token %}
                        		<button type="submit" class="btn btn-danger btn-sm">Delete</button>
								<a href="{% url 'core:edit-review' review.pk %}" class="btn btn-warning btn-sm">Edit</a>
                   			</form>
							
						</div>
                		{% endif %}
					</div>
				{% endfor %}
			</div>

			<h5>Leave a Review</h5>
			<div class="container">
				<form method="post">
					{% csrf_token %}
					<div class="form-group star-rating">
						<div>
							<i class="fa fa-star" data-rating="1"></i>
							<i class="fa fa-star" data-rating="2"></i>
							<i class="fa fa-star" data-rating="3"></i>
							<i class="fa fa-star" data-rating="4"></i>
							<i class="fa fa-star" data-rating="5"></i>
						</div>
						{{ form.rating }}
					</div>
					<div class="form-group">
						{{ form.comment.label_tag }}
						{{ form.comment }}
					</div>
					<button type="submit" class="btn btn-primary" style="margin-bottom: 5%;">Submit</button>
				</form>
			</div>


			<script>
				document.addEventListener('DOMContentLoaded', function () {
					const stars = document.querySelectorAll('.star-rating .fa-star');
					const ratingInput = document.querySelector('input[name="rating"]');
		
					stars.forEach(star => {
						star.addEventListener('click', function () {
							const rating = this.getAttribute('data-rating');
							ratingInput.value = rating;
							stars.forEach(s => {
								if (s.getAttribute('data-rating') <= rating) {
									s.classList.add('checked');
								} else {
									s.classList.remove('checked');
								}
							});
						});
					});
				});
			</script>
		</div>
	</section>
	<!-- Footer -->
	<footer class="bg6 p-t-45 p-b-43 p-l-45 p-r-45">
		<div class="flex-w p-b-90">
			<div class="w-size6 p-t-30 p-l-15 p-r-15 respon3">
				<h4 class="s-text12 p-b-30">
					GET IN TOUCH
				</h4>

				<div>
					<p class="s-text7 w-size27">
						Any questions? Let us know in store at Norrströmvägen 12B, 114 56 Stockholm, Sweden or call us on +46 8 123 4567
					</p>
				</div>
			</div>

		</div>

		<div class="t-center p-l-15 p-r-15">
			<a href="https://www.paypal.com/" target="_blank">
				<img class="h-size2" src="{% static 'images/icons/paypal.png' %}" alt="IMG-PAYPAL">
			</a>

			<a href="https://www.visa.com" target="_blank">
				<img class="h-size2" src="{% static 'images/icons/visa.png' %}" alt="IMG-VISA">
			</a>

			<a href="https://www.mastercard.us" target="_blank">
				<img class="h-size2" src="{% static 'images/icons/mastercard.png' %}" alt="IMG-MASTERCARD">
			</a>

			<a href="https://www.express.com/" target="_blank">
				<img class="h-size2" src="{% static 'images/icons/express.png' %}" alt="IMG-EXPRESS">
			</a>

			<a href="https://www.discover.com/" target="_blank">
				<img class="h-size2" src="{% static 'images/icons/discover.png' %}" alt="IMG-DISCOVER">
			</a>

			<div class="t-center s-text8 p-t-20">
				Copyright © 2024 All rights reserved.
			</div>
		</div>
	</footer>



	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="fa fa-angle-double-up" aria-hidden="true"></i>
		</span>
	</div>

	<!-- Container Selection -->
	<div id="dropDownSelect1"></div>
	<div id="dropDownSelect2"></div>

	{% endblock content %}